name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: npm install
        run: npm install

      - name: Run tests
        run: |
          npm run lint -- --no-fix --max-warnings 0
          npm run test:unit
          
      - name: Build and replace repository
        run: |
          npm run build -- --dest /tmp/build/
          ls -A1 | grep -vE "^.git$" | xargs rm -rf
          mv /tmp/build/* .

      - name: Commit replaced repository
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git branch -d gh-pages || true
          git checkout -b gh-pages
          git add .
          git commit -m 'Push built app to GitHub Pages'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: gh-pages
          force: true
